name: App

include:
  - App/Modules/ParentOne/ParentOne.yml
  - App/Modules/ParentTwo/ParentTwo.yml

options:
  createIntermediateGroups: true

targets:
  App:
    platform: iOS
    type: application
    info:
      path: App/Info.plist
      properties:
        UILaunchStoryboardName: LaunchScreen.storyboard
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: me.lievano.App
    sources:
      - path: App/Sources
      - path: App/Resources
    dependencies:
      - target: ParentOne
      - target: ParentTwo
  AppTests:
    platform: iOS
    type: bundle.unit-test
    info:
      path: App/Tests-Info.plist
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: me.lievano.AppTests
    sources:
      - path: App/Tests
    dependencies:
      - target: App
